Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "Creme de Cassis")
Ingredient.create(name: "Ale")
Ingredient.create(name: "Scotch")
Ingredient.create(name: "Orange bitters")
Cocktail.create(name:"Moscow Mule")
Cocktail.create(name:"Gin Basil Smash")
Dose.create(id_cocktails:"1", id_ingredients:"1")
